name: Check Case
on: 
  pull_request:
    types: [opened, edited, reopened]
jobs:
  check-case:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Case
        run: |
          for OUTPUT in $(find ./src -type d)
          do
            echo $OUTPUT
            if [[ $OUTPUT =~ [A-Z] ]]
            then
              echo "fail=true" >> $GITHUB_ENV
              echo $OUTPUT
            fi
          done
      - name: validate
        if: env.fail
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            :warning: **WARNING**: Your pull request has invalid capitalization.